services:
  front:
    build: ./front
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_SECRET=24230c0d373a2bba872b0893dc81ec00
      - NEXTAUTH_URL=http://109.196.101.51:3000
      - BACKEND_URL=http://back:8080
    depends_on:
      - back

  back:
    build: ./deploy
    ports:
      - '8080:8080'
    environment:
      - DB_NAME=psychosom
      - POSTGRES_USER=psychosom
      - POSTGRES_PASSWORD=psychosom348233083
      - DB_HOST=db
      - DB_PORT=5432
      - PSYHOSOM_WEB_URL=http://109.196.101.51:3000
      - PSYHOSOM_BOT_TOKEN=7849359674:AAGu7dC2hjt6JwchT6UIqjt64XHat5UrUH8
      - PSYHOSOM_BOT_USERNAME=psyhosom_test_1_bot
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: psychosom
      POSTGRES_USER: psychosom
      POSTGRES_PASSWORD: psychosom348233083
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
