spring:
  application:
    name: psihosom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/psihosom
    username: psihosom
    password: psihosom
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        boot.allow_jdbc_metadata_access: false
    database: postgresql
    open-in-view: false
    show-sql: true
  sql:
    init:
      mode: never

security:
  jwt:
    private-key-path: classpath:jwt/private_key.pem
    public-key-path: classpath:jwt/public_key.pem

frontend:
  url: ${PSIHOSOM_WEB_URL:http://localhost:3000}
