CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL
);

CREATE TABLE user_profile
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT REFERENCES app_user (id) NOT NULL UNIQUE,
    first_name        VARCHAR(255)                    NOT NULL,
    last_name         VARCHAR(255)                    NOT NULL,
    phone_number      VARCHAR(10),
    telegram_username VARCHAR(33)
);
